package ar.TpDisenio2019.DTO;
// Generated 24/11/2019 14:53:32 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * DTOAniodevehiculo generated by hbm2java
 */
public class DTOAniodevehiculo  {

	private int idAnioDeVehiculo;
	private Date anio;

	public DTOAniodevehiculo() {
	}

	public DTOAniodevehiculo(int idAnioDeVehiculo) {
		this.idAnioDeVehiculo = idAnioDeVehiculo;
	}

	public DTOAniodevehiculo(int idAnioDeVehiculo, Date anio) {
		this.idAnioDeVehiculo = idAnioDeVehiculo;
		this.anio = anio;
	}

	public int getIdAnioDeVehiculo() {
		return this.idAnioDeVehiculo;
	}

	public void setIdAnioDeVehiculo(int idAnioDeVehiculo) {
		this.idAnioDeVehiculo = idAnioDeVehiculo;
	}

	public Date getAnio() {
		return this.anio;
	}

	public void setAnio(Date anio) {
		this.anio = anio;
	}

}
