package ar.TpDisenio2019.DTO;
// Generated 24/11/2019 14:53:32 by Hibernate Tools 5.4.7.Final

/**
 * DTOCondicioniva generated by hbm2java
 */
public class DTOCondicioniva  {

	private int idCondicionIva;
	private String nombre;

	public DTOCondicioniva() {
	}

	public DTOCondicioniva(int idCondicionIva) {
		this.idCondicionIva = idCondicionIva;
	}

	public DTOCondicioniva(int idCondicionIva, String nombre) {
		this.idCondicionIva = idCondicionIva;
		this.nombre = nombre;
	}

	public int getIdCondicionIva() {
		return this.idCondicionIva;
	}

	public void setIdCondicionIva(int idCondicionIva) {
		this.idCondicionIva = idCondicionIva;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
