package ar.TpDisenio2019.DTO;
// Generated 24/11/2019 14:53:32 by Hibernate Tools 5.4.7.Final

import java.util.Date;



/**
 * DTOCliente generated by hbm2java
 */
public class DTOCliente  {

	private Integer idCliente;
	private Integer idEstadoCivil;
	private Integer idProfesion;
	private Integer idDireccion;
	private Integer idCondicionIva;
	private Integer idTipoDeDocumento;
	private Integer idEstadoCliente;
	private String nombre;
	private String apellido;
	private Integer nroDocumento;
	private String correoElectronico;
	private Date anioDeRegistro;
	private Integer nroCuil;
	private Integer nroCliente;

	public DTOCliente() {
	}

	public DTOCliente(Integer idEstadoCivil, Integer idProfesion, Integer idDireccion, Integer idCondicionIva,
			Integer idTipoDeDocumento, Integer idEstadoCliente, String nombre, String apellido, Integer nroDocumento,
			String correoElectronico, Date anioDeRegistro, Integer nroCuil, Integer nroCliente) {
		this.idEstadoCivil = idEstadoCivil;
		this.idProfesion = idProfesion;
		this.idDireccion = idDireccion;
		this.idCondicionIva = idCondicionIva;
		this.idTipoDeDocumento = idTipoDeDocumento;
		this.idEstadoCliente = idEstadoCliente;
		this.nombre = nombre;
		this.apellido = apellido;
		this.nroDocumento = nroDocumento;
		this.correoElectronico = correoElectronico;
		this.anioDeRegistro = anioDeRegistro;
		this.nroCuil = nroCuil;
		this.nroCliente = nroCliente;
	}

	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	public Integer getIdEstadoCivil() {
		return this.idEstadoCivil;
	}

	public void setIdEstadoCivil(Integer idEstadoCivil) {
		this.idEstadoCivil = idEstadoCivil;
	}

	public Integer getIdProfesion() {
		return this.idProfesion;
	}

	public void setIdProfesion(Integer idProfesion) {
		this.idProfesion = idProfesion;
	}

	public Integer getIdDireccion() {
		return this.idDireccion;
	}

	public void setIdDireccion(Integer idDireccion) {
		this.idDireccion = idDireccion;
	}

	public Integer getIdCondicionIva() {
		return this.idCondicionIva;
	}

	public void setIdCondicionIva(Integer idCondicionIva) {
		this.idCondicionIva = idCondicionIva;
	}

	public Integer getIdTipoDeDocumento() {
		return this.idTipoDeDocumento;
	}

	public void setIdTipoDeDocumento(Integer idTipoDeDocumento) {
		this.idTipoDeDocumento = idTipoDeDocumento;
	}

	public Integer getIdEstadoCliente() {
		return this.idEstadoCliente;
	}

	public void setIdEstadoCliente(Integer idEstadoCliente) {
		this.idEstadoCliente = idEstadoCliente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	

	public Integer getNroDocumento() {
		return this.nroDocumento;
	}

	public void setNroDocumento(Integer nroDocumento) {
		this.nroDocumento = nroDocumento;
	}

	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	public Date getAnioDeRegistro() {
		return this.anioDeRegistro;
	}

	public void setAnioDeRegistro(Date anioDeRegistro) {
		this.anioDeRegistro = anioDeRegistro;
	}

	public Integer getNroCuil() {
		return this.nroCuil;
	}

	public void setNroCuil(Integer nroCuil) {
		this.nroCuil = nroCuil;
	}

	public Integer getNrroCliente() {
		return this.nroCliente;
	}

	public void setNroCliente(Integer nroCliente) {
		this.nroCliente = nroCliente;
	}

}
