package ar.TpDisenio2019.DTO;
// Generated 24/11/2019 14:53:32 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * DTOCuota generated by hbm2java
 */
public class DTOCuota  {

	private int idCuotas;
	private Integer idRecibo;
	private Integer cuotasPagas;
	private Date vencimiento;
	private Float valorOriginal;
	private Float valorPorMora;
	private Float valorTotalaPagar;
	private Float bonificacion;
	private Float recargoPorMora;

	public DTOCuota() {
	}

	public DTOCuota(int idCuotas) {
		this.idCuotas = idCuotas;
	}

	public DTOCuota(int idCuotas, Integer idRecibo, Integer cuotasPagas, Date vencimiento, Float valorOriginal,
			Float valorPorMora, Float valorTotalaPagar, Float bonificacion, Float recargoPorMora) {
		this.idCuotas = idCuotas;
		this.idRecibo = idRecibo;
		this.cuotasPagas = cuotasPagas;
		this.vencimiento = vencimiento;
		this.valorOriginal = valorOriginal;
		this.valorPorMora = valorPorMora;
		this.valorTotalaPagar = valorTotalaPagar;
		this.bonificacion = bonificacion;
		this.recargoPorMora = recargoPorMora;
	}

	public int getIdCuotas() {
		return this.idCuotas;
	}

	public void setIdCuotas(int idCuotas) {
		this.idCuotas = idCuotas;
	}

	public Integer getIdRecibo() {
		return this.idRecibo;
	}

	public void setIdRecibo(Integer idRecibo) {
		this.idRecibo = idRecibo;
	}

	public Integer getCuotasPagas() {
		return this.cuotasPagas;
	}

	public void setCuotasPagas(Integer cuotasPagas) {
		this.cuotasPagas = cuotasPagas;
	}

	public Date getVencimiento() {
		return this.vencimiento;
	}

	public void setVencimiento(Date vencimiento) {
		this.vencimiento = vencimiento;
	}

	public Float getValorOriginal() {
		return this.valorOriginal;
	}

	public void setValorOriginal(Float valorOriginal) {
		this.valorOriginal = valorOriginal;
	}

	public Float getValorPorMora() {
		return this.valorPorMora;
	}

	public void setValorPorMora(Float valorPorMora) {
		this.valorPorMora = valorPorMora;
	}

	public Float getValorTotalaPagar() {
		return this.valorTotalaPagar;
	}

	public void setValorTotalaPagar(Float valorTotalaPagar) {
		this.valorTotalaPagar = valorTotalaPagar;
	}

	public Float getBonificacion() {
		return this.bonificacion;
	}

	public void setBonificacion(Float bonificacion) {
		this.bonificacion = bonificacion;
	}

	public Float getRecargoPorMora() {
		return this.recargoPorMora;
	}

	public void setRecargoPorMora(Float recargoPorMora) {
		this.recargoPorMora = recargoPorMora;
	}

}
