package ar.TpDisenio2019.DTO;
// Generated 24/11/2019 14:53:32 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * DTODatosdehijo generated by hbm2java
 */
public class DTODatosdehijo  {

	private int idDatosHijo;
	private Integer idEstadoCivil;
	private Date fecha;
	private String sexo;
	private Float porcentaje;

	public DTODatosdehijo() {
	}

	public DTODatosdehijo(int idDatosHijo) {
		this.idDatosHijo = idDatosHijo;
	}

	public DTODatosdehijo(int idDatosHijo, Integer idEstadoCivil, Date fecha, String sexo, Float porcentaje) {
		this.idDatosHijo = idDatosHijo;
		this.idEstadoCivil = idEstadoCivil;
		this.fecha = fecha;
		this.sexo = sexo;
		this.porcentaje = porcentaje;
	}

	public int getIdDatosHijo() {
		return this.idDatosHijo;
	}

	public void setIdDatosHijo(int idDatosHijo) {
		this.idDatosHijo = idDatosHijo;
	}

	public Integer getIdEstadoCivil() {
		return this.idEstadoCivil;
	}

	public void setIdEstadoCivil(Integer idEstadoCivil) {
		this.idEstadoCivil = idEstadoCivil;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public Float getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Float porcentaje) {
		this.porcentaje = porcentaje;
	}

}
