package ar.TpDisenio2019.DTO;
// Generated 24/11/2019 14:53:32 by Hibernate Tools 5.4.7.Final

/**
 * DTODireccion generated by hbm2java
 */
public class DTODireccion {

	private int idDireccion;
	private Integer idLocalidad;
	private String calle;
	private Integer numero;
	private Integer piso;
	private String departamento;

	public DTODireccion() {
	}

	public DTODireccion(int idDireccion) {
		this.idDireccion = idDireccion;
	}

	public DTODireccion(int idDireccion, Integer idLocalidad, String calle, Integer numero, Integer piso,
			String departamento) {
		this.idDireccion = idDireccion;
		this.idLocalidad = idLocalidad;
		this.calle = calle;
		this.numero = numero;
		this.piso = piso;
		this.departamento = departamento;
	}

	public int getIdDireccion() {
		return this.idDireccion;
	}

	public void setIdDireccion(int idDireccion) {
		this.idDireccion = idDireccion;
	}

	public Integer getIdLocalidad() {
		return this.idLocalidad;
	}

	public void setIdLocalidad(Integer idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public Integer getPiso() {
		return this.piso;
	}

	public void setPiso(Integer piso) {
		this.piso = piso;
	}

	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

}
