package ar.TpDisenio2019.DTO;
// Generated 24/11/2019 14:53:32 by Hibernate Tools 5.4.7.Final

/**
 * DTOEstado generated by hbm2java
 */
public class DTOEstado  {

	private int idEstado;
	private String tipo;

	public DTOEstado() {
	}

	public DTOEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	public DTOEstado(int idEstado, String tipo) {
		this.idEstado = idEstado;
		this.tipo = tipo;
	}

	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
