package ar.TpDisenio2019.DTO;
// Generated 24/11/2019 14:53:32 by Hibernate Tools 5.4.7.Final

/**
 * DTOEstadocliente generated by hbm2java
 */
public class DTOEstadocliente  {

	private int idEstadoCliente;
	private String tipo;

	public DTOEstadocliente() {
	}

	public DTOEstadocliente(int idEstadoCliente) {
		this.idEstadoCliente = idEstadoCliente;
	}

	public DTOEstadocliente(int idEstadoCliente, String tipo) {
		this.idEstadoCliente = idEstadoCliente;
		this.tipo = tipo;
	}

	public int getIdEstadoCliente() {
		return this.idEstadoCliente;
	}

	public void setIdEstadoCliente(int idEstadoCliente) {
		this.idEstadoCliente = idEstadoCliente;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
