package ar.TpDisenio2019.DTO;
// Generated 24/11/2019 14:53:32 by Hibernate Tools 5.4.7.Final

/**
 * DTOFormasdepago generated by hbm2java
 */
public class DTOFormasdepago  {

	private int idFormasDePago;
	private String nombre;

	public DTOFormasdepago() {
	}

	public DTOFormasdepago(int idFormasDePago) {
		this.idFormasDePago = idFormasDePago;
	}

	public DTOFormasdepago(int idFormasDePago, String nombre) {
		this.idFormasDePago = idFormasDePago;
		this.nombre = nombre;
	}

	public int getIdFormasDePago() {
		return this.idFormasDePago;
	}

	public void setIdFormasDePago(int idFormasDePago) {
		this.idFormasDePago = idFormasDePago;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
