package ar.TpDisenio2019.DTO;
// Generated 24/11/2019 14:53:32 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * DTOModificacionpoliza generated by hbm2java
 */
public class DTOModificacionpoliza  {

	private int idModificacionPoliza;
	private int idVehiculo;
	private int idMedidasSeguridad;
	private int idDatosHijo;
	private int idTipoCobertura;
	private int identNroPoliza;
	private Date anio;
	private String patente;
	private String motor;
	private String chasis;
	private String nroSiniestro;
	private Integer kmPorAnio;
	private Float montoTotal;

	public DTOModificacionpoliza() {
	}

	public DTOModificacionpoliza(int idModificacionPoliza, int idVehiculo, int idMedidasSeguridad, int idDatosHijo,
			int idTipoCobertura, int identNroPoliza) {
		this.idModificacionPoliza = idModificacionPoliza;
		this.idVehiculo = idVehiculo;
		this.idMedidasSeguridad = idMedidasSeguridad;
		this.idDatosHijo = idDatosHijo;
		this.idTipoCobertura = idTipoCobertura;
		this.identNroPoliza = identNroPoliza;
	}

	public DTOModificacionpoliza(int idModificacionPoliza, int idVehiculo, int idMedidasSeguridad, int idDatosHijo,
			int idTipoCobertura, int identNroPoliza, Date anio, String patente, String motor, String chasis,
			String nroSiniestro, Integer kmPorAnio, Float montoTotal) {
		this.idModificacionPoliza = idModificacionPoliza;
		this.idVehiculo = idVehiculo;
		this.idMedidasSeguridad = idMedidasSeguridad;
		this.idDatosHijo = idDatosHijo;
		this.idTipoCobertura = idTipoCobertura;
		this.identNroPoliza = identNroPoliza;
		this.anio = anio;
		this.patente = patente;
		this.motor = motor;
		this.chasis = chasis;
		this.nroSiniestro = nroSiniestro;
		this.kmPorAnio = kmPorAnio;
		this.montoTotal = montoTotal;
	}

	public int getIdModificacionPoliza() {
		return this.idModificacionPoliza;
	}

	public void setIdModificacionPoliza(int idModificacionPoliza) {
		this.idModificacionPoliza = idModificacionPoliza;
	}

	public int getIdVehiculo() {
		return this.idVehiculo;
	}

	public void setIdVehiculo(int idVehiculo) {
		this.idVehiculo = idVehiculo;
	}

	public int getIdMedidasSeguridad() {
		return this.idMedidasSeguridad;
	}

	public void setIdMedidasSeguridad(int idMedidasSeguridad) {
		this.idMedidasSeguridad = idMedidasSeguridad;
	}

	public int getIdDatosHijo() {
		return this.idDatosHijo;
	}

	public void setIdDatosHijo(int idDatosHijo) {
		this.idDatosHijo = idDatosHijo;
	}

	public int getIdTipoCobertura() {
		return this.idTipoCobertura;
	}

	public void setIdTipoCobertura(int idTipoCobertura) {
		this.idTipoCobertura = idTipoCobertura;
	}

	public int getIdentNroPoliza() {
		return this.identNroPoliza;
	}

	public void setIdentNroPoliza(int identNroPoliza) {
		this.identNroPoliza = identNroPoliza;
	}

	public Date getAnio() {
		return this.anio;
	}

	public void setAnio(Date anio) {
		this.anio = anio;
	}

	public String getPatente() {
		return this.patente;
	}

	public void setPatente(String patente) {
		this.patente = patente;
	}

	public String getMotor() {
		return this.motor;
	}

	public void setMotor(String motor) {
		this.motor = motor;
	}

	public String getChasis() {
		return this.chasis;
	}

	public void setChasis(String chasis) {
		this.chasis = chasis;
	}

	public String getNroSiniestro() {
		return this.nroSiniestro;
	}

	public void setNroSiniestro(String nroSiniestro) {
		this.nroSiniestro = nroSiniestro;
	}

	public Integer getKmPorAnio() {
		return this.kmPorAnio;
	}

	public void setKmPorAnio(Integer kmPorAnio) {
		this.kmPorAnio = kmPorAnio;
	}

	public Float getMontoTotal() {
		return this.montoTotal;
	}

	public void setMontoTotal(Float montoTotal) {
		this.montoTotal = montoTotal;
	}

}
