package ar.TpDisenio2019.DTO;
// Generated 24/11/2019 14:53:32 by Hibernate Tools 5.4.7.Final

/**
 * DTOModelo generated by hbm2java
 */
public class DTOModelo  {

	private int idModelo;
	private int idMarca;
	private Integer idAnioDeVehiculo;
	private String nombre;
	private Float porcentaje;

	public DTOModelo() {
	}

	public DTOModelo(int idModelo, int idMarca) {
		this.idModelo = idModelo;
		this.idMarca = idMarca;
	}

	public DTOModelo(int idModelo, int idMarca, Integer idAnioDeVehiculo, String nombre, Float porcentaje) {
		this.idModelo = idModelo;
		this.idMarca = idMarca;
		this.idAnioDeVehiculo = idAnioDeVehiculo;
		this.nombre = nombre;
		this.porcentaje = porcentaje;
	}

	public int getIdModelo() {
		return this.idModelo;
	}

	public void setIdModelo(int idModelo) {
		this.idModelo = idModelo;
	}

	public int getIdMarca() {
		return this.idMarca;
	}

	public void setIdMarca(int idMarca) {
		this.idMarca = idMarca;
	}

	public Integer getIdAnioDeVehiculo() {
		return this.idAnioDeVehiculo;
	}

	public void setIdAnioDeVehiculo(Integer idAnioDeVehiculo) {
		this.idAnioDeVehiculo = idAnioDeVehiculo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Float getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Float porcentaje) {
		this.porcentaje = porcentaje;
	}

}
