package ar.TpDisenio2019.DTO;
// Generated 24/11/2019 14:53:32 by Hibernate Tools 5.4.7.Final

/**
 * DTOMarca generated by hbm2java
 */
public class DTOMarca  {

	private int idMarca;
	private String marca;

	public DTOMarca() {
	}

	public DTOMarca(int idMarca) {
		this.idMarca = idMarca;
	}

	public DTOMarca(int idMarca, String marca) {
		this.idMarca = idMarca;
		this.marca = marca;
	}

	public int getIdMarca() {
		return this.idMarca;
	}

	public void setIdMarca(int idMarca) {
		this.idMarca = idMarca;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

}
