package ar.TpDisenio2019.DTO;
// Generated 24/11/2019 14:53:32 by Hibernate Tools 5.4.7.Final

/**
 * DTOMedidasdeseguridadporc generated by hbm2java
 */
public class DTOMedidasdeseguridadporc  {

	private int idMedPorc;

	public DTOMedidasdeseguridadporc() {
	}

	public DTOMedidasdeseguridadporc(int idMedPorc) {
		this.idMedPorc = idMedPorc;
	}

	public int getIdMedPorc() {
		return this.idMedPorc;
	}

	public void setIdMedPorc(int idMedPorc) {
		this.idMedPorc = idMedPorc;
	}

}
