package ar.TpDisenio2019.DTO;
// Generated 24/11/2019 14:53:32 by Hibernate Tools 5.4.7.Final

/**
 * DTOOperador generated by hbm2java
 */
public class DTOOperador  {

	private int idOperador;
	private String nombre;

	public DTOOperador() {
	}

	public DTOOperador(int idOperador) {
		this.idOperador = idOperador;
	}

	public DTOOperador(int idOperador, String nombre) {
		this.idOperador = idOperador;
		this.nombre = nombre;
	}

	public int getIdOperador() {
		return this.idOperador;
	}

	public void setIdOperador(int idOperador) {
		this.idOperador = idOperador;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
