package ar.TpDisenio2019.DTO;
// Generated 24/11/2019 14:53:32 by Hibernate Tools 5.4.7.Final

/**
 * DTOPais generated by hbm2java
 */
public class DTOPais  {

	private int idPais;
	private String nombre;

	public DTOPais() {
	}

	public DTOPais(int idPais) {
		this.idPais = idPais;
	}

	public DTOPais(int idPais, String nombre) {
		this.idPais = idPais;
		this.nombre = nombre;
	}

	public int getIdPais() {
		return this.idPais;
	}

	public void setIdPais(int idPais) {
		this.idPais = idPais;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
