package ar.TpDisenio2019.DTO;
// Generated 24/11/2019 14:53:32 by Hibernate Tools 5.4.7.Final

/**
 * DTOProvincia generated by hbm2java
 */
public class DTOProvincia  {

	private int idProvincia;
	private Integer idPais;
	private String nombre;

	public DTOProvincia() {
	}

	public DTOProvincia(int idProvincia) {
		this.idProvincia = idProvincia;
	}

	public DTOProvincia(int idProvincia, Integer idPais, String nombre) {
		this.idProvincia = idProvincia;
		this.idPais = idPais;
		this.nombre = nombre;
	}

	public int getIdProvincia() {
		return this.idProvincia;
	}

	public void setIdProvincia(int idProvincia) {
		this.idProvincia = idProvincia;
	}

	public Integer getIdPais() {
		return this.idPais;
	}

	public void setIdPais(Integer idPais) {
		this.idPais = idPais;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
