package ar.TpDisenio2019.DTO;
// Generated 24/11/2019 14:53:32 by Hibernate Tools 5.4.7.Final

/**
 * DTOProfesion generated by hbm2java
 */
public class DTOProfesion  {

	private int idProfesion;
	private String nombre;

	public DTOProfesion() {
	}

	public DTOProfesion(int idProfesion) {
		this.idProfesion = idProfesion;
	}

	public DTOProfesion(int idProfesion, String nombre) {
		this.idProfesion = idProfesion;
		this.nombre = nombre;
	}

	public int getIdProfesion() {
		return this.idProfesion;
	}

	public void setIdProfesion(int idProfesion) {
		this.idProfesion = idProfesion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
