package ar.TpDisenio2019.DTO;
// Generated 24/11/2019 14:53:32 by Hibernate Tools 5.4.7.Final

/**
 * DTOTipodedocumento generated by hbm2java
 */
public class DTOTipodedocumento  {

	private Integer idTipoDeDocumento;
	private String nombre;

	public DTOTipodedocumento() {
	}

	public DTOTipodedocumento(String nombre) {
		this.nombre = nombre;
	}

	public Integer getIdTipoDeDocumento() {
		return this.idTipoDeDocumento;
	}

	public void setIdTipoDeDocumento(Integer idTipoDeDocumento) {
		this.idTipoDeDocumento = idTipoDeDocumento;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
