package ar.TpDisenio2019.Modelo;
// Generated 17/11/2019 18:40:49 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DTOLocalidad generated by hbm2java
 */
@Entity
@Table(name = "localidad", catalog = "dbelaseguradov4")
public class Localidad  {

	private int idLocalidad;
	private Integer idProvincia;
	private String nombre;

	public Localidad() {
	}

	public Localidad(int idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	public Localidad(int idLocalidad, Integer idProvincia, String nombre) {
		this.idLocalidad = idLocalidad;
		this.idProvincia = idProvincia;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "idLocalidad", unique = true, nullable = false)
	public int getIdLocalidad() {
		return this.idLocalidad;
	}

	public void setIdLocalidad(int idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	@Column(name = "idProvincia")
	public Integer getIdProvincia() {
		return this.idProvincia;
	}

	public void setIdProvincia(Integer idProvincia) {
		this.idProvincia = idProvincia;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
