package ar.TpDisenio2019.Modelo;
// Generated 17/11/2019 18:40:49 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DTOMedidasdeseguridadporc generated by hbm2java
 */
@Entity
@Table(name = "medidasdeseguridadporc", catalog = "dbelaseguradov4")
public class Medidasdeseguridadporc {

	private int idMedPorc;

	public Medidasdeseguridadporc() {
	}

	public Medidasdeseguridadporc(int idMedPorc) {
		this.idMedPorc = idMedPorc;
	}

	@Id

	@Column(name = "idMedPorc", unique = true, nullable = false)
	public int getIdMedPorc() {
		return this.idMedPorc;
	}

	public void setIdMedPorc(int idMedPorc) {
		this.idMedPorc = idMedPorc;
	}

}
